name: Java CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Compile and Test
        run: |
          javac -d . Person.java PersonTest.java
          java -cp . org.junit.runner.JUnitCore PersonTest
